#!/usr/bin/env python3
# Copyright 2026 Blackboard Studios
# SPDX-License-Identifier: Apache-2.0
"""Generate Windows Winget manifests for a Hamstik CLI release.

cargo-dist has no winget integration, so per the decision record
(design/INSTALL.md §Winget) the pipeline generates versioned manifests into
`winget/BlackboardStudios.HamstikCLI/<version>/` and a maintainer opens the
PR to microsoft/winget-pkgs per stable release. The manifests reference the
public release URLs and their sha256 digests only — no credentials, no
environment-specific configuration.

Usage:

    python3 scripts/generate_winget_manifests.py \
        --version 0.1.1 --tag v0.1.1 --sha256sum target/distrib/sha256.sum \
        --date 2026-09-15 [--out winget]

Exits nonzero on any inconsistency (missing digest, unexpected format) so a
release never ships broken manifests.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

PACKAGE_ID = "BlackboardStudios.HamstikCLI"
# The Windows zip unpacks to a hamstik-cli-<triple>/ directory (cargo-dist
# layout); winget portable packages point at the exe inside it.
WINDOWS_TRIPLE = "x86_64-pc-windows-msvc"
ARCHIVE_NAME = f"hamstik-cli-{WINDOWS_TRIPLE}.zip"
RELATIVE_EXE = f"hamstik-cli-{WINDOWS_TRIPLE}/hamstik.exe"
HOME_PAGE = "https://hamstik.com"
DESCRIPTION = (
    "Official command-line interface for Hamstik — manage projects, work "
    "items, automation, CI/CD, and coding-agent workflows from the terminal."
)
# SPDX license expression; the CLI is Apache-2.0.
LICENSE = "Apache-2.0"
LICENSE_URL = "https://github.com/blackboardstudios/hamstik-cli/blob/main/LICENSE"


def fail(message: str) -> None:
    print(f"winget manifest generation FAILED: {message}", file=sys.stderr)
    sys.exit(1)


def load_digests(sha256sum_path: Path) -> dict[str, str]:
    digests: dict[str, str] = {}
    try:
        for line in sha256sum_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            digest, sep, name = line.partition(" *")
            if not sep:
                digest, sep, name = line.partition("  ")
            name = name.strip().lstrip("*")
            if not sep or not re.fullmatch(r"[0-9a-f]{64}", digest):
                fail(f"malformed sha256.sum line: {line!r}")
            digests[name] = digest
    except OSError as error:
        fail(f"cannot read {sha256sum_path}: {error}")
    return digests


def check_semver(version: str) -> None:
    # Winget rejects prerelease versions in the community repo; the manifest
    # generator is only run for stable releases.
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        fail(
            f"version {version!r} is not a stable X.Y.Z — winget manifests are "
            "only generated for stable releases"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Winget manifests for a Hamstik CLI release."
    )
    parser.add_argument("--version", required=True, help="release version (X.Y.Z)")
    parser.add_argument("--tag", required=True, help="release git tag (vX.Y.Z)")
    parser.add_argument(
        "--sha256sum",
        required=True,
        type=Path,
        help="path to the release sha256.sum",
    )
    parser.add_argument(
        "--date",
        required=True,
        help="release date in YYYY-MM-DD (used as ReleaseDate)",
    )
    parser.add_argument(
        "--out",
        default="winget",
        type=Path,
        help="output root directory (default: winget/)",
    )
    args = parser.parse_args(argv)

    check_semver(args.version)
    if not re.fullmatch(r"v\d+\.\d+\.\d+", args.tag):
        fail(f"tag {args.tag!r} is not a stable vX.Y.Z tag")
    try:
        release_date = datetime.date.fromisoformat(args.date).isoformat()
    except ValueError:
        fail(f"--date {args.date!r} is not YYYY-MM-DD")

    digests = load_digests(args.sha256sum)
    digest = digests.get(ARCHIVE_NAME)
    if digest is None:
        fail(f"{ARCHIVE_NAME} is missing from {args.sha256sum}")
    installer_url = (
        f"https://github.com/blackboardstudios/hamstik-cli/releases/"
        f"download/{args.tag}/{ARCHIVE_NAME}"
    )
    release_notes_url = (
        "https://github.com/blackboardstudios/hamstik-cli/releases/tag/"
        f"{args.tag}"
    )
    publisher = "Blackboard Studios"
    package = "Hamstik CLI"

    out_dir = args.out / PACKAGE_ID / args.version
    out_dir.mkdir(parents=True, exist_ok=True)

    # --- version manifest ---
    version_manifest = f"""# Generated by scripts/generate_winget_manifests.py; do not edit.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: {PACKAGE_ID}
PackageVersion: {args.version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
"""
    (out_dir / f"{PACKAGE_ID}.yaml").write_text(version_manifest, encoding="utf-8")

    # --- installer manifest ---
    installer_manifest = f"""# Generated by scripts/generate_winget_manifests.py; do not edit.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: {PACKAGE_ID}
PackageVersion: {args.version}
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: {release_date}
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: {RELATIVE_EXE}
    PortableCommandAlias: hamstik
  InstallerUrl: {installer_url}
  InstallerSha256: {digest.upper()}
ManifestType: installer
ManifestVersion: 1.6.0
"""
    (out_dir / f"{PACKAGE_ID}.installer.yaml").write_text(
        installer_manifest, encoding="utf-8"
    )

    # --- locale manifest ---
    locale_manifest = f"""# Generated by scripts/generate_winget_manifests.py; do not edit.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: {PACKAGE_ID}
PackageVersion: {args.version}
PackageLocale: en-US
Publisher: {publisher}
PublisherUrl: {HOME_PAGE}
PackageName: {package}
PackageUrl: {HOME_PAGE}
License: {LICENSE}
LicenseUrl: {LICENSE_URL}
ShortDescription: {DESCRIPTION}
Description: {DESCRIPTION}
ReleaseNotesUrl: {release_notes_url}
InstallationNotes: >-
  The hamstik binary is installed as a portable command (hamstik). Verify
  downloads with sha256sum -c sha256.sum and gh attestation verify.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
"""
    (out_dir / f"{PACKAGE_ID}.locale.en-US.yaml").write_text(
        locale_manifest, encoding="utf-8"
    )

    print(f"generated 3 winget manifests in {out_dir}")
    for path in sorted(out_dir.iterdir()):
        print(f"  {path.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())