.TH HAMSTIK 1 "HAMSTIK RELEASE ANNOUNCEMENT DRAFT SHOW"
.SH NAME
hamstik release announcement draft show \- Show the active announcement draft
.SH SYNOPSIS
.B hamstik release announcement draft show [OPTIONS]
.SH DESCRIPTION
Show the active announcement draft
.SH ARGUMENTS
.TP
.I RELEASE_ID
Release version id (UUID)
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
