.TH HAMSTIK 1 "HAMSTIK SQUEAKQL CACHE"
.SH NAME
hamstik squeakql cache \- Inspect or clear the local saved\-query cache (fully offline)
.SH SYNOPSIS
.B hamstik squeakql cache <COMMAND>
.SH DESCRIPTION
Inspect or clear the local saved\-query cache (fully offline)
.SH SUBCOMMANDS
See subcommand pages for details.
