.TH HAMSTIK 1 "HAMSTIK CONFIG GET"
.SH NAME
hamstik config get \- Get a single configuration value
.SH SYNOPSIS
.B hamstik config get [OPTIONS]
.SH DESCRIPTION
Get a single configuration value
.SH ARGUMENTS
.TP
.I KEY
Configuration key: `profile`, `organization`, `project`, `editor`, `pager`, `output`, `git_branch_template`, or `audit_log`
