.TH HAMSTIK 1 "HAMSTIK CONFIG SET"
.SH NAME
hamstik config set \- Set a configuration value
.SH SYNOPSIS
.B hamstik config set [OPTIONS]
.SH DESCRIPTION
Set a configuration value
.SH ARGUMENTS
.TP
.I KEY
Configuration key (e.g. `editor`, `pager`, `output`, `profile`)
.TP
.I VALUE
New value for the key
