.TH HAMSTIK 1 "HAMSTIK USER AVATAR"
.SH NAME
hamstik user avatar \- Download a user's avatar
.SH SYNOPSIS
.B hamstik user avatar [OPTIONS]
.SH DESCRIPTION
Download a user's avatar
.SH ARGUMENTS
.TP
.I PUBLIC_ID
The user's public ID (usr_...)
.SH OPTIONS
.TP
.B -o, --output
Output path (defaults to the public ID with a content-type derived extension)
.TP
.B --avatar-version
Opaque avatar version cache selector
.TP
.B --format
Opaque avatar format selector
.TP
.B --revision
Opaque avatar revision cache selector
