.TH HAMSTIK 1 "HAMSTIK WORK ATTACHMENT DELETE"
.SH NAME
hamstik work attachment delete \- Delete an attachment (creator or Organization administrator)
.SH SYNOPSIS
.B hamstik work attachment delete [OPTIONS]
.SH DESCRIPTION
Delete an attachment (creator or Organization administrator)
.SH ARGUMENTS
.TP
.I KEY
Work item key
.TP
.I ATTACHMENT_ID
Attachment id (UUID)
