.TH HAMSTIK 1 "HAMSTIK WORK UNARCHIVE"
.SH NAME
hamstik work unarchive \- Unarchive a work item (Organization administrators)
.SH SYNOPSIS
.B hamstik work unarchive [OPTIONS]
.SH DESCRIPTION
Unarchive a work item (Organization administrators)
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --force
Bypass revision conflict protection (If-Match: *)
Choices: true, false
.TP
.B --idempotency-key
Explicit idempotency key
