.TH HAMSTIK 1 "HAMSTIK WORK WATCHER UNMUTE"
.SH NAME
hamstik work watcher unmute \- Stop suppressing notifications
.SH SYNOPSIS
.B hamstik work watcher unmute [OPTIONS]
.SH DESCRIPTION
Stop suppressing notifications
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --idempotency-key
Explicit idempotency key
