.TH HAMSTIK 1 "HAMSTIK WORK WATCHER MUTE"
.SH NAME
hamstik work watcher mute \- Keep watching but suppress notifications
.SH SYNOPSIS
.B hamstik work watcher mute [OPTIONS]
.SH DESCRIPTION
Keep watching but suppress notifications
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --idempotency-key
Explicit idempotency key
