.TH HAMSTIK 1 "HAMSTIK SCHEDULE RUN"
.SH NAME
hamstik schedule run \- Run a saved schedule definition (the external scheduler's entry point)
.SH SYNOPSIS
.B hamstik schedule run [OPTIONS]
.SH DESCRIPTION
Run a saved schedule definition (the external scheduler's entry point)
.SH ARGUMENTS
.TP
.I NAME
Schedule name
