.TH HAMSTIK 1 "HAMSTIK RELEASE ANNOUNCEMENT REVISION"
.SH NAME
hamstik release announcement revision \- Read one historical published announcement revision
.SH SYNOPSIS
.B hamstik release announcement revision [OPTIONS]
.SH DESCRIPTION
Read one historical published announcement revision
.SH ARGUMENTS
.TP
.I RELEASE_ID
Release version id (UUID)
.TP
.I REVISION
Announcement revision number
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
