.TH HAMSTIK 1 "HAMSTIK CONFIG UNSET"
.SH NAME
hamstik config unset \- Remove a configuration value
.SH SYNOPSIS
.B hamstik config unset [OPTIONS]
.SH DESCRIPTION
Remove a configuration value
.SH ARGUMENTS
.TP
.I KEY
Configuration key to remove: `profile`, `organization`, `project`, `editor`, `pager`, `output`, `git_branch_template`, or `audit_log`
