.TH HAMSTIK 1 "HAMSTIK ATTRIBUTE LIST"
.SH NAME
hamstik attribute list \- List Organization definitions and product limits
.SH SYNOPSIS
.B hamstik attribute list [OPTIONS]
.SH DESCRIPTION
List Organization definitions and product limits
.SH OPTIONS
.TP
.B --include-retired
Include retired definitions
Choices: true, false
