.TH HAMSTIK 1 "HAMSTIK WORK WATCHER UNWATCH"
.SH NAME
hamstik work watcher unwatch \- Stop watching a work item
.SH SYNOPSIS
.B hamstik work watcher unwatch [OPTIONS]
.SH DESCRIPTION
Stop watching a work item
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --idempotency-key
Explicit idempotency key
