.TH HAMSTIK 1 "HAMSTIK RELEASE TRANSITIONS"
.SH NAME
hamstik release transitions \- List allowed release state transitions
.SH SYNOPSIS
.B hamstik release transitions [OPTIONS]
.SH DESCRIPTION
List allowed release state transitions
.SH ARGUMENTS
.TP
.I ID
Release version id (UUID)
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
