.TH HAMSTIK 1 "HAMSTIK ATTRIBUTE OPTION RETIRE"
.SH NAME
hamstik attribute option retire \- Retire an option while preserving already assigned values
.SH SYNOPSIS
.B hamstik attribute option retire [OPTIONS]
.SH DESCRIPTION
Retire an option while preserving already assigned values
.SH ARGUMENTS
.TP
.I ATTRIBUTE_KEY
Stable Attribute key
.TP
.I OPTION_KEY
Stable option key
.SH OPTIONS
.TP
.B --idempotency-key
Explicit idempotency key
