.TH HAMSTIK 1 "HAMSTIK _HAMSTIK_DYN_COMPLETE"
.SH NAME
hamstik _hamstik_dyn_complete \- Internal: dynamic shell completion for live values
.SH SYNOPSIS
.B hamstik _hamstik_dyn_complete [OPTIONS]
.SH DESCRIPTION
Internal: dynamic shell completion for live values
.SH ARGUMENTS
.TP
.I TYP
Completion candidate type
.TP
.I PREFIX
Prefix to filter candidates
