.TH HAMSTIK 1 "HAMSTIK AUTH LOGIN"
.SH NAME
hamstik auth login \- Authenticate with a Personal Access Token
.SH SYNOPSIS
.B hamstik auth login [OPTIONS]
.SH DESCRIPTION
Authenticate with a Personal Access Token
.SH OPTIONS
.TP
.B --with-token
Read the token from stdin instead of prompting
Choices: true, false
