.TH HAMSTIK 1 "HAMSTIK RELEASE ITEM LIST"
.SH NAME
hamstik release item list \- List the release versions a Work Item belongs to
.SH SYNOPSIS
.B hamstik release item list [OPTIONS]
.SH DESCRIPTION
List the release versions a Work Item belongs to
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
