.TH HAMSTIK 1 "HAMSTIK SPRINT TRANSITIONS"
.SH NAME
hamstik sprint transitions \- List allowed sprint state transitions
.SH SYNOPSIS
.B hamstik sprint transitions [OPTIONS]
.SH DESCRIPTION
List allowed sprint state transitions
.SH ARGUMENTS
.TP
.I ID
Sprint id (UUID)
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
