.TH HAMSTIK 1 "HAMSTIK RELEASE"
.SH NAME
hamstik release \- Work with Project release versions, announcements, and audit packages
.SH SYNOPSIS
.B hamstik release <COMMAND>
.SH DESCRIPTION
Work with Project release versions, announcements, and audit packages
.SH SUBCOMMANDS
See subcommand pages for details.
