.TH HAMSTIK 1 "HAMSTIK WORK WATCHER WATCH"
.SH NAME
hamstik work watcher watch \- Watch a work item (start receiving notifications)
.SH SYNOPSIS
.B hamstik work watcher watch [OPTIONS]
.SH DESCRIPTION
Watch a work item (start receiving notifications)
.SH ARGUMENTS
.TP
.I KEY
Work item key
.SH OPTIONS
.TP
.B --idempotency-key
Explicit idempotency key
