.TH HAMSTIK 1 "HAMSTIK PROJECT ARCHIVE"
.SH NAME
hamstik project archive \- Archive a project (Organization administrators only)
.SH SYNOPSIS
.B hamstik project archive [OPTIONS]
.SH DESCRIPTION
Archive a project (Organization administrators only)
.SH ARGUMENTS
.TP
.I KEY
Project key
.SH OPTIONS
.TP
.B --force
Bypass revision conflict protection (If-Match: *)
Choices: true, false
.TP
.B --idempotency-key
Explicit idempotency key
