.TH HAMSTIK 1 "HAMSTIK DASHBOARD RUN"
.SH NAME
hamstik dashboard run \- Evaluate an Advanced Dashboard at its current revision
.SH SYNOPSIS
.B hamstik dashboard run [OPTIONS]
.SH DESCRIPTION
Evaluate an Advanced Dashboard at its current revision
.SH ARGUMENTS
.TP
.I ID
Advanced Dashboard UUID
.SH OPTIONS
.TP
.B --filters-file
Optional JSON file containing AdvancedDashboardFilters (`-` for stdin)
