.TH HAMSTIK 1 "HAMSTIK RELEASE ANNOUNCEMENT CURRENT"
.SH NAME
hamstik release announcement current \- Read the latest published announcement
.SH SYNOPSIS
.B hamstik release announcement current [OPTIONS]
.SH DESCRIPTION
Read the latest published announcement
.SH ARGUMENTS
.TP
.I RELEASE_ID
Release version id (UUID)
.SH OPTIONS
.TP
.B --project
Project key (overrides context)
