.TH HAMSTIK 1 "HAMSTIK RELEASE ANNOUNCEMENT DRAFT"
.SH NAME
hamstik release announcement draft \- Work with the editable announcement draft
.SH SYNOPSIS
.B hamstik release announcement draft <COMMAND>
.SH DESCRIPTION
Work with the editable announcement draft
.SH SUBCOMMANDS
See subcommand pages for details.
